'use strict';
const A=EflowAssessment,$=id=>document.getElementById(id),names={baseline:'Baseline · usable evidence',entry:'Entry · baseline unavailable',top:'Top · priority + resources + site study','short-record':'Baseline · short but usable record','bounds-blocked':'Blocked · bounds cross','evidence-missing':'Blocked · daily operand missing','designation-pending':'Designation pending',designated:'Hypothetical valid designation'};
const outputNames={entry_floor_candidate:'Illustrative floor only',seasonal_quantity_candidate:'Seasonal quantity candidate',habitat_element_candidate:'Habitat element candidate',potential_pending:'Potential sizing pending',receptor_pending:'Receptor sizing pending',track_undetermined:'Track undetermined',calculation_pending:'Calculation pending',route_only_natural:'Natural route · calculation pending'};
const fmt=(n,d=2)=>Number(n).toLocaleString(EflowI18n.dateLocale(),{maximumFractionDigits:d,minimumFractionDigits:d});
let passport=null;
$('case-select').replaceChildren(...Object.entries(A.CASES).map(([id,c])=>new Option(id+' · '+c.name,id)));
function fillVariants(id,variant='baseline'){$('variant-select').replaceChildren(...A.CASES[id].variants.map(v=>new Option(id==='R2'&&v==='baseline'?'Natural route · evidence pending':!['R1','R2'].includes(id)?'Route and evidence gaps':names[v],v)));$('variant-select').value=variant;}
function list(target,values){$(target).replaceChildren(...values.map(v=>{const el=document.createElement('li');el.textContent=v;return el;}));}
function render(id,variant,updateURL=true){
 passport=A.buildPassport(id,variant);const p=passport;$('invalid').hidden=true;$('case-result').hidden=false;$('case-select').value=id;fillVariants(id,variant);document.querySelectorAll('[data-case]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.case===id)));
 if(updateURL)history.replaceState(null,'','?'+EflowI18n.keepQuery(new URLSearchParams({case:id,variant})).toString());
 $('route-title').textContent=id+' · '+A.CASES[id].name;$('route-subtitle').textContent='Origin: '+p.origin.replaceAll('_',' ')+' · Designation: '+p.designation+' · Track: '+p.track;
 list('route-reasons',p.reasons);$('designation-note').textContent=p.designationEvidence+(p.designation==='designated'?'. Natural origin remains; no artificial subtype and no prior natural result are supplied.':'. Physical alteration alone does not change the track.');
 $('eligibility').textContent=id==='R1'?'Entry needs usable low-flow/table operands. Baseline needs usable reference and daily bounds. Top additionally needs priority, resources and a site study. Short record length alone does not force entry.':'Resolve the origin and designation first, then establish route-specific evidence. Natural-track rungs cannot fill a missing potential or receptor calculation.';
 $('output-title').textContent=outputNames[p.outputKind];$('output-explanation').textContent=p.rung?'Selected rung: '+p.rung+'. This is a teaching candidate; final requirement and delivery obligation remain pending.':p.nextAction;$('uncertainty').textContent='Uncertainty: '+p.uncertainty+(variant==='short-record'?'. Hypothetical eligibility toggle: the same 100-year synthetic arithmetic is retained. This is not a short-record numerical experiment.':'');
 $('attempts').hidden=!p.attempts.length;$('attempt-rows').replaceChildren(...p.attempts.map(a=>{const tr=document.createElement('tr');[({eligible_N_rungs:'Eligible natural-track rungs',donor_transfer:'Donor transfer',presumptive:'Presumptive rule',habitat:'Habitat route',velocity_depth:'Velocity / depth route',service_if_applicable:'Service route, where applicable',regulated_winter_share_suspended:'Regulated winter share · suspended'})[a.route]||a.route,a.applicability||a.result,(a.missingInputs||[]).join('; ')+(a.limitation?' · '+a.limitation:'')].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td);});return tr;}));
 const vals=p.seasonalCandidate?[[fmt(p.seasonalCandidate.annualVolumeMm3)+' million m³','Candidate over 365 days'],[fmt(p.seasonalCandidate.juneVolumeMm3)+' million m³','Candidate volume in June'],[fmt(p.seasonalCandidate.juneMeanM3s)+' m³/s','June mean · not daily compliance']]:p.floorCandidate?[[fmt(p.floorCandidate.value,3)+' m³/s','Illustrative low-flow floor'],['Pending','Seasonal ecological regime'],['Pending','Final requirement']]:[['Pending','Sizing or track decision'],['Not established','Ecological status'],['Action recorded','No substitute zero']];
 $('numbers').replaceChildren(...vals.map(([value,label])=>{const e=document.createElement('div');e.className='number';const b=document.createElement('b'),s=document.createElement('span');b.textContent=value;s.textContent=label;e.append(b,s);return e;}));
 $('calculation-note').textContent=p.rung==='baseline'?'100 synthetic years → 50% annual design class → use 75% class magnitude and shape → 70.00 million m³. June carries 20.45%: 14.31 million m³ / 30 days / 86,400 seconds = 5.52 m³/s. Daily bounds checked: no crossing. These rounded values describe the canonical R1 fixture.':p.rung==='entry'?'The floor is 0.263 m³/s. A constant floor is one ingredient; it must not be promoted to a complete seasonal regime.':p.rung==='top'?'Hypothetical seasonal habitat curves select a lower qualifying flow. More water can reduce suitability; a flow pass does not guarantee habitat attainment. This single element is not a holistic top-tier assessment.':p.outputKind==='calculation_pending'?'Eligible natural rungs are unavailable in this fixture. Donor qualification is missing, and the presumptive rule is unadopted. Keep the result pending.':p.nextAction;
 $('scope').textContent='Not computed: '+p.omittedLimbs.join(', ')+'. Final requirement and delivery obligation need an authority decision. Delivery and deliverability are not established for this method case.';
 $('candidate-chart').replaceChildren();if(p.reference){const series=[{v:p.reference.dailyMeanM3s,c:'#9aa9a4',label:'Synthetic naturalised reference'},{v:p.seasonalCandidate?.dailyMeanM3s||(p.floorCandidate?Array(365).fill(p.floorCandidate.value):null),c:p.rung==='top'?'#b95c23':p.rung==='entry'?'#087e9d':'#7955a0',label:outputNames[p.outputKind]}].filter(s=>s.v);const max=Math.max(...series.flatMap(s=>s.v))*1.05;const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 1000 240');svg.setAttribute('role','img');svg.setAttribute('aria-label','Daily teaching candidate and synthetic naturalised reference, m³/s');svg.innerHTML='<text x="35" y="20" font-size="12" fill="#576e69">Daily mean flow · m³/s</text>'+series.map(s=>'<path d="'+s.v.map((v,i)=>(i?'L':'M')+(40+i/364*925)+','+(200-v/max*165)).join(' ')+'" fill="none" stroke="'+s.c+'" stroke-width="3"/>').join('')+'<text x="40" y="225" font-size="12">Jan</text><text x="500" y="225" font-size="12">Jul</text><text x="930" y="225" font-size="12">Dec</text>';const legend=document.createElement('p');legend.className='small';legend.textContent='Grey: synthetic naturalised reference. Coloured: '+(p.rung?outputNames[p.outputKind]:'no candidate is available')+'. Availability equals reference in this preset; delivery is not measured.';$('candidate-chart').append(svg,legend);}
 $('playground-link').hidden=id!=='R1';$('playground-link').href='playground.html?workshop=R1&variant='+variant;$('basin-link').hidden=id!=='R1';$('bridge-note').hidden=id!=='R1';
 const rows=[['Water body / checkpoint',p.waterBodyId+' / '+p.checkpoint],['Reference',p.referenceId||'Pending — reach evidence not supplied'],['Candidate',outputNames[p.outputKind]],['Final requirement','Pending — omitted limbs / authority decision'],['Available water',p.availableWater?'Synthetic daily input':'Not supplied'],['Deliverable / delivered','Not established / not available'],['Quality / ecological status','Not assessed / not established']];$('passport-summary').replaceChildren(...rows.flatMap(([a,b])=>{const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=a;dd.textContent=b;return[dt,dd];}));$('next-action').textContent=p.responsibleRole+': '+p.nextAction;$('review-trigger').textContent='Review when: '+p.reviewTrigger+'.';$('passport-json').textContent=JSON.stringify(p,null,2);
}
$('case-select').onchange=()=>render($('case-select').value,'baseline');$('variant-select').onchange=()=>render($('case-select').value,$('variant-select').value);document.querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>render(b.dataset.case,'baseline'));
$('download-passport').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(EflowI18n.withLocale(passport),null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=passport.waterBodyId+'-'+$('variant-select').value+'-assessment-passport.json';a.hidden=true;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);};
const initial=A.context(location.search);if(initial.valid)render(initial.caseId,initial.variant,false);else{$('invalid').hidden=false;$('invalid').textContent=initial.message;$('case-result').hidden=true;$('case-select').selectedIndex=-1;}
