/* Guided teaching routes. No official designation, ecological status or adopted prescription. */
(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('./playground-engine.js'):root.EflowPlayground);if(typeof module==='object'&&module.exports)module.exports=api;else root.EflowAssessment=api;})(typeof globalThis!=='undefined'?globalThis:this,function(engine){
'use strict';
const CONFIG=Object.freeze({pattern:'snowmelt',meanFlow:3.35258513536549,supplyFactor:1,designClass:50,entryScale:1,riskFloor:0.1,habitatTarget:0.7});
const CASES=Object.freeze({R1:{name:'Natural irrigation river',origin:'natural',variants:['baseline','entry','top','short-record','bounds-blocked','evidence-missing']},R2:{name:'Altered natural receiving reach',origin:'natural',variants:['baseline','designation-pending','designated']},C1:{name:'Artificial canal',origin:'artificial',subtype:'canal',variants:['baseline']},D1:{name:'Collector-drain',origin:'artificial',subtype:'collector-drain',variants:['baseline']},S1:{name:'Reservoir',origin:'artificial',subtype:'reservoir',variants:['baseline']},W1:{name:'Wetland receptor, supply unknown',origin:'natural',receptor:{kind:'wetland',connectivity:'unknown'},variants:['baseline']}});
const DESIGNATIONS=['none','not_searched','pending','designated','expired','rejected'];
const unavailable=(reason,nextAction='Obtain and review supporting evidence',responsibleRole='Basin assessment lead',reviewTrigger='New evidence or changed pressure')=>({value:null,reason,nextAction,responsibleRole,reviewTrigger});
function context(search,page='assessment'){
 const p=new URLSearchParams(search),key=page==='playground'?'workshop':page==='basin'?'workshopCase':'case';
 const requested=[...p.keys()].length>0,id=p.get(key)||(!requested?'R1':null),variant=p.get('variant')||'baseline';
 const allowed=page==='basin'?[key,'node']:[key,'variant'];
 const valid=!!id&&Object.hasOwn(CASES,id)&&CASES[id].variants.includes(variant)&&![...p.keys()].some(k=>!allowed.includes(k)||p.getAll(k).length!==1)&&(page!=='playground'||id==='R1')&&(page!=='basin'||id==='R1'&&p.get('node')==='wb-upstream');
 return {valid,requested,caseId:valid?id:null,variant:valid?variant:null,message:valid?'':'Invalid workshop context. Choose a listed case; no route has been calculated.'};
}
function classify(origin,designation='none'){
 if(!DESIGNATIONS.includes(designation))throw new RangeError('Unknown designation state');
 if(!['natural','artificial','natural_receptor'].includes(origin)||['not_searched','pending'].includes(designation))return 'undetermined';
 if(origin==='natural_receptor')return 'receptor';
 return origin==='artificial'||designation==='designated'?'potential':'natural/status';
}
function preset(variant){const c={...CONFIG};if(variant==='bounds-blocked')c.riskFloor=20;if(variant==='evidence-missing')c.riskFloor=null;return c;}
function isCanonical(config,variant='baseline'){const expected=preset(variant);return Object.keys(expected).every(k=>config[k]===expected[k]);}
function buildPassport(id='R1',variant='baseline'){
 if(!Object.hasOwn(CASES,id)||!CASES[id].variants.includes(variant))throw new RangeError('Invalid case/variant combination');
 const c=CASES[id],designation=variant==='designation-pending'?'pending':variant==='designated'?'designated':'none',track=c.receptor?'receptor':classify(c.origin,designation);
 const pending=unavailable('No adopted final prescription is established by this teaching calculation','Complete omitted limbs and obtain the competent authority’s decision','Competent authority and assessment lead');
 const p={schemaVersion:'eflow-passport/2',migrationNote:'Version 2 separates W1 natural origin from receptor assessment and replaces the previously asserted R2 carrier path with unknown.',datasetId:'workshop-r1-synthetic-v1',waterBodyId:id,technicalReachId:id+'-teaching-reach',referenceId:id==='R1'?'synthetic-100year-median-v1':null,checkpoint:id+'-teaching-checkpoint',period:{start:'2025-01-01',end:'2025-12-31',kind:'synthetic design year'},timeSupport:{flow:'daily mean',annual:'365 days',june:'30 days'},units:{flow:'m³/s',annualVolume:'million m³',habitatScore:'dimensionless'},evidenceKind:'synthetic-method-calculation',origin:c.origin,designation,designationEvidence:'Fictional assumed records check; no real legal assignment',artificialSubtype:c.subtype||null,track,rung:null,reasons:[],outputKind:null,floorCandidate:null,seasonalCandidate:null,finalRequirement:null,deliveryObligation:null,availableWater:null,deliverableWater:null,deliveredWater:null,retainedPriorRequirement:null,pending:{finalRequirement:pending,deliveryObligation:pending,deliverableWater:unavailable('Network deliverability has not been assessed','Evaluate feasible delivery at this checkpoint','System operator'),deliveredWater:{...unavailable('No observed or simulated delivery series exists for this method case','Acquire delivery evidence with matching location and time support','Monitoring authority'),evidenceKind:'not_available'},retainedPriorRequirement:unavailable('No prior natural-track result supplied','Check the versioned assessment record')},ecologicalStatus:'not established',uncertainty:variant==='short-record'?'Raised: short record assumed usable for teaching':'Synthetic, unvalidated operands',omittedLimbs:['Winter provision','Spawning correction','Quality adjustment','Biological status assessment'],assumptions:['Fictional conceptual basin; proposed crosswalk, not official designations.','Naturalised reference represents a present-climate counterfactual without abstraction/regulation; this synthetic generator is not an accepted reconstruction.','Route colours are not ecological-status classes.','A quantity candidate does not establish ecological adequacy.'],nextAction:'Complete evidence and omitted limbs; review the candidate',responsibleRole:'Basin assessment lead',reviewTrigger:'New monitoring evidence, changed pressures or scheduled review',attempts:[]};
 if(track==='undetermined'){p.outputKind='track_undetermined';p.reasons=['Designation is pending: tier selection is blocked'];p.nextAction='Resolve designation and record validity';p.responsibleRole='Competent designation authority';}
 else if(track==='receptor'){p.outputKind='receptor_pending';p.omittedLimbs=['Receptor level target','Inundation duration and area','Receptor quality targets','Carrier-path hydraulics','Biological response'];p.reasons=['W1 has its own level, inundation and quality targets; a river-flow pass cannot establish them'];p.targetLocation='W1 wetland';p.carrierPath=null;p.nextAction='Define receptor targets and obtain stage–area–inundation and connectivity evidence';}
 else if(track==='potential'){
  p.outputKind='potential_pending';p.omittedLimbs=['Potential objectives and applicable sizing route','Protected-function safeguards','Salt / thermal targets','Ecological potential assessment'];p.reasons=[c.origin==='natural'?'Hypothetical valid designation changes the objective track; natural origin remains':'Artificial origin uses the potential track'];
  p.attempts=[{route:'habitat',applicability:'To be established',missingInputs:['Potential objective','Site habitat study']},{route:'velocity_depth',applicability:'To be established',missingInputs:['Hydraulic geometry','Protected functions and targets']},{route:'service_if_applicable',applicability:c.subtype==='canal'?'C1 teaching carrier function assumed; ecological applicability unresolved':['collector-drain','reservoir'].includes(c.subtype)?'Establish carrier function and stated service duty before applying this route':'No service sizing justified by this fixture',missingInputs:['Operating-rule / approving-act delivery schedule, otherwise permit entitlement','Conveyance loss','Ecological safeguards'],limitation:'Service flow is not derived from observed abstraction and does not establish ecological adequacy'},{route:'regulated_winter_share_suspended',applicability:'Suspended — not executable',missingInputs:['Resolved method basis']}];
  p.nextAction='Establish applicable potential route and required inputs; keep salt/thermal targets separate from flow sizing';p.assumptions.push('No natural-track fallback substitutes for a missing potential route.');
 }else if(id==='R2'){p.outputKind='route_only_natural';p.reasons=['Alteration and irrigation use alone do not change natural origin or the status track'];p.nextAction='Assess rung eligibility and collect reach-specific operands';}
 else{
  const config=preset(variant),r=engine.runExperiment(config);p.config=config;p.availableWater={evidenceKind:'synthetic-input',dailyMeanM3s:r.available};p.reference={evidenceKind:'synthetic-reference',dailyMeanM3s:r.reference,recordYears:100};p.assumptions.push(...r.assumptions);if(variant==='short-record')p.assumptions.push('Hypothetical short-record eligibility toggle only: unchanged 100-year synthetic arithmetic is retained; this is not a short-record numerical experiment.');
  if(['bounds-blocked','evidence-missing'].includes(variant)){p.outputKind='calculation_pending';p.reasons=[r.methods[1].reason,'Other natural rungs are not executable in this fixture'];p.attempts=[{route:'eligible_N_rungs',result:'Unavailable under fixture evidence'},{route:'donor_transfer',result:'Pending — donor qualification missing'},{route:'presumptive',result:'Pending — rule unadopted and inputs unspecified'}];p.boundsCrossing=r.diagnostics.firstCrossing;p.nextAction='Resolve daily operands or qualify donor evidence; do not substitute an unadopted value';}
  else if(variant==='entry'){p.rung='entry';p.outputKind='entry_floor_candidate';p.floorCandidate={value:r.methods[0].requirement[0],unit:'m³/s',kind:'illustrative floor only'};p.reasons=['Baseline evidence unavailable; entry operands assumed usable; top not eligible'];p.assumptions.push('Constant floor is not a complete seasonal ecological regime.');}
  else{const top=variant==='top',m=r.methods[top?2:1];p.rung=top?'top':'baseline';p.outputKind=top?'habitat_element_candidate':'seasonal_quantity_candidate';p.seasonalCandidate={kind:p.outputKind,dailyMeanM3s:m.requirement,annualVolumeMm3:m.annualVolumeMm3,juneVolumeMm3:m.requirement.slice(151,181).reduce((a,b)=>a+b,0)*86400/1e6,juneMeanM3s:m.requirement.slice(151,181).reduce((a,b)=>a+b,0)/30};p.reasons=[top?'Priority, resources and hypothetical site study supplied; single habitat element only':variant==='short-record'?'Short but assumed usable record retains baseline route with raised uncertainty':'Baseline evidence assumed usable; no priority study selects top'];p.boundsCrossing=r.diagnostics.firstCrossing;if(top)p.habitatPerformance=r.diagnostics.habitatPerformance;}
 }
 for(const key of ['floorCandidate','seasonalCandidate','availableWater'])if(p[key]===null)p.pending[key]=unavailable(key==='seasonalCandidate'&&variant==='entry'?'Entry supplies a floor only; full seasonal regime remains pending':'Not computed for this selected route',p.nextAction,p.responsibleRole);
 return p;
}
function experimentRecord(config,result,variant='baseline') {return {schemaVersion:'eflow-experiment/1',datasetId:isCanonical(config,variant)?'workshop-r1-synthetic-v1':'modified-synthetic-experiment',evidenceKind:'synthetic-method-calculation',contextOnly:{waterBodyId:'R1',variant,canonical:isCanonical(config,variant)},config:{...config},result,finalRequirement:unavailable('Exploration does not adopt a requirement'),ecologicalStatus:'not established'};}
function exportExperiment(config,result,urlContext){return urlContext.requested&&urlContext.valid?experimentRecord(config,result,urlContext.variant):{schemaVersion:'eflow-experiment/1',datasetId:'generic-synthetic-experiment',evidenceKind:'synthetic-method-calculation',config:{...config},result};}
function savedPassport(r,waterBodyId,scenarioIndex,day,contextOnly=null){
 const w=r.water_bodies.find(w=>w.identifier===waterBodyId);if(!w)throw new RangeError('Unknown saved water body');if(!Number.isInteger(day)||day<0||day>=r.dates.length)throw new RangeError('Invalid saved day');
 return {schemaVersion:'eflow-saved-passport/1',datasetId:'saved-basin-2025-v1',waterBodyId:w.identifier,technicalReachId:w.identifier,referenceId:'saved-normal-unregulated-reference-v1',checkpoint:w.identifier,scenarioId:'saved-scenario-'+scenarioIndex,scenarioName:r.scenario.name,scenario:r.scenario,period:{start:r.dates[0],end:r.dates.at(-1)},selectedDate:r.dates[day],timeSupport:'Daily means; full-year findings',units:{flow:'m³/s',salt:'mg/L'},evidenceKind:'saved-synthetic-simulation',flowM3s:w.flow_m3s,normalReferenceM3s:w.reference_m3s,flowCriterionM3s:w.requirement_m3s,flowCriterionBasis:'Fixed 30% of normal reference; independent of workshop candidates',saltMgL:w.salt_mg_l,saltCriterionMgL:r.scenario.salt_limit_mg_l,findings:w.assessment,selectedDay:{flowM3s:w.flow_m3s[day],flowCriterionM3s:w.requirement_m3s[day],saltMgL:w.salt_mg_l[day]},observedDelivery:unavailable('No observations; saved synthetic simulation'),deliverableWater:unavailable('These operating scenarios do not establish a deliverability bound'),ecologicalStatus:'not established',contextOnly,assumptions:['No new workshop target was passed to TaqSim or Fishy.','Daily means do not establish subdaily extrema.','Flow/quality findings do not establish ecological status.'],provenance:r.provenance};
}
return {CONFIG,CASES,DESIGNATIONS,context,classify,preset,isCanonical,buildPassport,experimentRecord,exportExperiment,savedPassport};
});
