/* Browser orchestration: immutable saved evidence and separate teaching arithmetic. */
(function(){'use strict';
const C=window.EflowLearningContent,L=window.EflowLearning,G=window.EflowGuided,P=window.EflowPlayground;
const base=window.EflowGuidedData,sharing=window.EflowGuidedSharing;
const params=new URLSearchParams(location.search);let preferred='en';try{preferred=localStorage.getItem('eflow-language')||'en';}catch(_error){}
const bounded=(key,fallback,lo,hi)=>{const x=params.has(key)?Number(params.get(key)):fallback;return Number.isFinite(x)&&x>=lo&&x<=hi?x:fallback;};
let state={lang:C.locales.includes(params.get('lang'))?params.get('lang'):C.locales.includes(preferred)?preferred:'en',exercise:Math.round(bounded('exercise',1,1,6)),day:Math.round(bounded('day',181,0,364)),body:params.get('body')||'R2',mode:params.get('mode')==='network'?'network':'landscape',scenario:params.get('scenario')==='normal-managed'?'normal-managed':'dry-managed-sharing',plan:params.get('plan')==='1',origin:params.get('origin')==='artificial'?'artificial':'natural',designation:['none','designated'].includes(params.get('designation'))?params.get('designation'):'not_searched',irrigation:bounded('irrigation',1,0,1),days:Math.round(bounded('days',30,1,365)),factor:bounded('factor',1,0,1),pattern:['snowmelt','rainfall','buffered','drought'].includes(params.get('pattern'))?params.get('pattern'):'snowmelt',supply:bounded('supply',1,0,1.5),risk:['missing','cross'].includes(params.get('risk'))?params.get('risk'):'supplied',value:bounded('value',7,0,12),halfWidth:bounded('halfWidth',.5,0,3),missing:params.get('missing')==='1',attribute:params.get('attribute')==='1',answer:null,revealed:false,variant:Math.round(bounded('variant',0,0,10000))};
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const t=k=>{const value=C.catalogs[state.lang][k];if(value===undefined)throw new Error('Missing translation: '+k);return value;};
const n=(value,d=3)=>value===null||!Number.isFinite(value)?t('unknown'):new Intl.NumberFormat(state.lang,{maximumFractionDigits:d}).format(value);
const lesson=()=>{const original=C.catalogs[state.lang].lessons[state.exercise-1];return state.variant%2?{...original,question:t('retryQ'+state.exercise),options:[t('retryA'+state.exercise),t('retryB'+state.exercise)],answer:0,feedback:t('retryA'+state.exercise)+'. '+original.feedback}:original;};
const compare=()=>G.validateComparison(base,sharing);
function url(){const p=new URLSearchParams();for(const [k,v]of Object.entries(state)){if(['answer','revealed'].includes(k))continue;p.set(k,typeof v==='boolean'?(v?'1':'0'):v);}return 'learn.html?'+p;}
function persist(){history.replaceState(null,'',url());}
function link(page,key){const p=new URLSearchParams({lang:state.lang,returnTo:url()});return `<a href="${page}?${esc(p.toString())}">${esc(t(key))} ↗</a>`;}
const p=text=>`<p>${esc(text)}</p>`;
const card=(label,value,unit='',tone='')=>`<div class="card ${tone}"><div class="note">${esc(label)}</div><div class="value">${esc(value)}</div><div class="unit">${esc(unit)}</div></div>`;
function details(title,body,open=false){return `<details${open?' open':''}><summary>${esc(title)}</summary><div>${body}</div></details>`;}
function svg(title,inside,caption='',height=300){return `<figure class="visual"><svg viewBox="0 0 900 ${height}" role="img" aria-label="${esc(title)}"><title>${esc(title)}</title><defs><marker id="arrow" markerWidth="9" markerHeight="9" refX="7" refY="3" orient="auto"><path d="M0,0 L8,3 L0,6" fill="#437f82"/></marker></defs>${inside}</svg>${caption?`<figcaption>${esc(caption)}</figcaption>`:''}</figure>`;}
const txt=(x,y,value,cls='',anchor='start')=>`<text x="${x}" y="${y}" class="${cls}" text-anchor="${anchor}">${esc(value)}</text>`;
const line=(x1,y1,x2,y2,color='#437f82',width=4,dash='')=>`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${color}" stroke-width="${width}" ${dash?'stroke-dasharray="'+dash+'"':''} marker-end="url(#arrow)"/>`;
function chart(series,title,shade=null){const valid=series.filter(s=>Array.isArray(s.values)&&s.values.length&&s.values.every(Number.isFinite));if(!valid.length)return `<p class="pending">${esc(t('unavailable'))}</p>`;const max=Math.max(.1,...valid.flatMap(s=>s.values))*1.12;const x=(i,len)=>55+i/(len-1)*810,y=v=>245-v/max*205;let out='';for(let i=0;i<5;i++){const v=max*i/4;out+=`<line x1="55" y1="${y(v)}" x2="865" y2="${y(v)}" stroke="#dbe3db"/>`+txt(45,y(v)+4,n(v,1),'small','end');}if(shade){const a=shade[0],b=shade[1];const path=a.map((v,i)=>`${x(i,a.length)},${y(v)}`).join(' ')+ ' '+[...b].reverse().map((v,j)=>`${x(b.length-1-j,b.length)},${y(v)}`).join(' ');out+=`<polygon points="${path}" fill="#eecfb9" opacity=".65"/>`;}valid.forEach(s=>{out+=`<polyline points="${s.values.map((v,i)=>`${x(i,s.values.length).toFixed(1)},${y(v).toFixed(1)}`).join(' ')}" fill="none" stroke="${s.color}" stroke-width="${s.width||3}" ${s.dash?'stroke-dasharray="7 5"':''}/>`;});out+=txt(55,20,t('flow'),'small')+txt(55,275,'1','small')+txt(455,275,t('day'),'small','middle')+txt(865,275,valid[0].values.length,'small','end');return svg(title,out,'',295)+`<div class="legend">${valid.map(s=>`<span class="key" style="--key:${s.color}">${esc(s.label)}${s.dash?' · · ·':''}</span>`).join('')}</div>`;}
function selection(id,label,options,value){return `<label for="${id}">${esc(label)}<select id="${id}" aria-label="${esc(label)}">${options.map(([v,label])=>`<option value="${esc(v)}"${String(v)===String(value)?' selected':''}>${esc(label)}</option>`).join('')}</select></label>`;}
function range(id,label,value,min,max,step){return `<label for="${id}">${esc(label)}: ${n(value)}<input aria-label="${esc(label)}" id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${value}"></label>`;}
function check(id,label,value){return `<label class="inline"><input type="checkbox" id="${id}"${value?' checked':''}>${esc(label)}</label>`;}
function networkFigure(){let s='';if(state.mode==='landscape'){s+='<path d="M0 140 L110 28 L175 88 L245 15 L340 115 L430 60 L565 135 L720 65 L900 150 V350 H0Z" fill="#e5e9dc"/><path d="M75 58 L111 28 L142 68 L120 61 L107 70Z" fill="#fff"/><path d="M215 57 L245 15 L280 64 L252 50 L235 62Z" fill="#fff"/><path d="M0 210 Q260 120 480 240 T900 220 V355 H0Z" fill="#eef0df"/>';}
if(state.plan)s+='<rect x="430" y="150" width="435" height="135" rx="25" fill="#e0d8ed" opacity=".55" stroke="#795bb0" stroke-dasharray="8 5"/>'+txt(440,305,'PU-demo · '+t('plan'),'small');
s+=`<path d="M90 115 Q180 110 240 180 T430 215 L575 215 L800 215" fill="none" stroke="#96c7d2" stroke-width="${state.mode==='landscape'?24:10}"/><path d="M240 180 L310 80 L495 80 L575 215" fill="none" stroke="#b99358" stroke-width="9"/>`;
s+=line(90,115,210,170)+line(280,207,393,215)+line(455,215,545,215)+line(598,215,792,215)+line(249,169,302,90,'#b99358')+line(328,80,480,80,'#b99358')+line(510,94,565,195,'#b99358');
s+='<rect x="389" y="185" width="55" height="62" rx="12" fill="#a4d0d8" stroke="#457888"/><ellipse cx="724" cy="75" rx="78" ry="29" fill="#c3d9b8" stroke="#7d9e70"/><circle cx="575" cy="215" r="8" fill="#fff" stroke="#245f75" stroke-width="3"/><path d="M790 197 L810 197 L810 233 L790 233Z" fill="#fff" stroke="#795bb0" stroke-width="3"/>';
s+=txt(105,85,'R1')+txt(338,60,'C1')+txt(526,123,'D1')+txt(417,277,'S1','','middle')+txt(500,198,'R2a','','middle')+txt(680,198,'R2b','','middle')+txt(720,80,'W1 · ?','','middle')+txt(798,260,t('checkpoint'),'small','middle')+txt(655,340,'R2 · '+t('body'),'','middle');
s+='<path d="M458 323 L458 310 M458 318 L850 318 M850 310 L850 323" stroke="#157466" fill="none" stroke-width="2"/>';
const selected={R1:'M90 115 Q180 110 240 180',R2:'M455 215 L800 215',C1:'M240 180 L310 80 L495 80',D1:'M495 80 L575 215',S1:'M389 183 L445 183 L445 249 L389 249 Z',W1:'M650 75 Q720 20 800 75 Q720 130 650 75'};s+=`<path d="${selected[state.body]||selected.R2}" fill="none" stroke="#157466" stroke-width="5" stroke-dasharray="5 4"/>`+txt(30,342,t('body')+': '+state.body,'small');return svg(t(state.mode),s,lesson().intro,365);}
function exerciseOne(){const track=G.classify({origin:state.origin,designation:state.designation,designationValidity:state.designation==='designated'?'valid':null});return `<div class="controls">${selection('mode',t('mode' in C.catalogs[state.lang]?'mode':'evidence'),[['landscape',t('landscape')],['network',t('network')]],state.mode)}${check('plan',t('plan'),state.plan)}${selection('body',t('body'),['R1','R2','C1','D1','S1','W1'].map(x=>[x,x]),state.body)}</div>${networkFigure()}<div class="controls">${selection('origin',t('origin'),[['natural',t('naturalOrigin')],['artificial',t('artificial')]],state.origin)}${selection('designation',t('designation'),[['not_searched',t('notSearched')],['none',t('none')],['designated',t('validDesignation')]],state.designation)}</div>${state.revealed?`<div class="grid two">${card(t('body'),state.body)}${card(t('status'),t(track==='potential'?'potentialRoute':track==='natural/status'?'statusRoute':'undetermined'))}</div>`:''}`;}
function timingFigure(){const a=Array.from({length:48},(_,i)=>3+2*Math.sin(i/48*2*Math.PI)),b=Array.from({length:48},(_,i)=>3+2*Math.sin((i+12)/48*2*Math.PI));return chart([{values:a,color:'#24769a',label:'A'},{values:b,color:'#b45d28',label:'B'}],t('timing'))+p(t('timingNote'));}
function habitatFigure(){let s='<rect x="50" y="55" width="210" height="120" rx="12" fill="#3b8b75"/><rect x="285" y="55" width="210" height="120" rx="12" fill="#d4dfb0"/>';s+=txt(155,105,'100 m² × 0.8','','middle')+txt(390,105,'100 m² × 0.2','','middle')+txt(155,148,'80 m²','','middle')+txt(390,148,'20 m²','','middle')+txt(520,120,'Σ = 100 m²');s+='<polyline points="620,170 665,110 715,60 760,35 820,105" fill="none" stroke="#795bb0" stroke-width="4"/><line x1="600" y1="175" x2="860" y2="175" stroke="#536a70"/><line x1="600" y1="30" x2="600" y2="175" stroke="#536a70"/>';s+=txt(720,205,'Q (m³/s)','','middle');return svg(t('top'),s,t('topStory'),235);}
function methodLab(){let run;try{run=P.runExperiment({pattern:state.pattern,meanFlow:5,supplyFactor:state.supply,designClass:50,riskFloor:state.risk==='missing'?null:state.risk==='cross'?50:.8,habitatTarget:.7});}catch(_error){return p(t('badInput'));}const names=['entry','baseline','top'],colors=['#24769a','#157466','#795bb0'];return p(t('labNote'))+`<div class="controls">${selection('pattern',t('pattern'),['snowmelt','rainfall','buffered','drought'].map(v=>[v,t(v)]),state.pattern)}${range('supply',t('supply'),state.supply,0,1.5,.1)}${selection('risk',t('risk'),[['supplied',t('supplied')],['missing',t('riskMissing')],['cross',t('riskCross')]],state.risk)}</div>`+chart([{values:run.reference,label:t('natural'),color:'#90a5a5',dash:true},{values:run.available,label:t('available'),color:'#b45d28'},...run.methods.map((m,i)=>({values:m.requirement,label:t(names[i]),color:colors[i]}))],t('laboratory'))+`<div class="grid">${run.methods.map((m,i)=>card(t(names[i]),m.requirement?n(m.annualVolumeMm3):t('unavailable'),t('volume'),['blue','teal','orange'][i])).join('')}</div><div class="table-wrap"><table><thead><tr><th>${t('component')}</th><th>${t('status')}</th></tr></thead><tbody><tr><td>${t('pattern')} / ${t('class50')}</td><td>${t('supplied')}</td></tr><tr><td>${t('baseline')}</td><td>${t(run.methods[1].requirement?'computed':'unavailable')}</td></tr><tr><td>${t('risk')}</td><td>${t(state.risk==='missing'?'unavailable':'supplied')}</td></tr><tr><td>${t('missingLimbs')}</td><td>${t('unavailable')}</td></tr></tbody></table></div>`;}
function savedAnnualArithmetic(){const ref=base.reference,m=base.method,seconds=365*86400,mean=ref.annualVolumeMm3*1e6/seconds,a=m.shiftFactor,v0=ref.dailyM3s[0]*86400,raw=ref.annualVolumeMm3*a;return `<h4>${t('annualArithmeticTitle')}</h4>${p(t('annualArithmeticScope'))}<ol><li>${p(t('annualInterpolation'))}<p class="note">r₅₀ = 0.50 × 101 = 50.5; a₅₀ = (${n(ref.annualFactors[49],9)} + ${n(ref.annualFactors[50],9)}) / 2 = 1<br>r₇₅ = 0.75 × 101 = 75.75<br>a₇₅ = a₇₅ᵗʰ + 0.75 × (a₇₆ᵗʰ − a₇₅ᵗʰ) = ${n(ref.annualFactors[74],9)} + 0.75 × (${n(ref.annualFactors[75],9)} − ${n(ref.annualFactors[74],9)}) = 229/330 ≈ ${n(a,9)}</p></li><li>${p(t('annualMagnitude'))}<p class="note">V₅₀ = Σ(Qref(t) × 86 400) = ${n(ref.annualVolumeMm3,6)} Mm³<br>Q̄₅₀ = V₅₀ × 10⁶ / (365 × 86 400) = ${n(mean,9)} m³/s<br>V₇₅ = V₅₀ × 229/330 = ${n(raw,9)} Mm³</p></li><li>${p(t('annualShape'))}<p class="note">s(t) = Qref(t) / Q̄₅₀; mean(s) = 1<br>Qclass(t) = Q̄₅₀ × (229/330) × s(t) = Qref(t) × (229/330)</p></li><li>${p(t('annualRounding'))}<p class="note">Veco(t) = 2 × ceil(Vref(t) × (229/330) / 2)<br>${esc(base.dates[0])}: Vref = ${n(v0,3)} m³; Vref × (229/330) = ${n(v0*a,6)} m³ → Veco = ${n(m.ecologicalM3s[0]*86400,3)} m³<br>Qeco = Veco / 86 400 = ${n(m.ecologicalM3s[0],9)} m³/s<br>Σ Veco(t) = ${n(m.annualVolumeMm3,6)} Mm³; Δround = ${n((m.annualVolumeMm3-raw)*1e6,6)} m³</p></li></ol>${p(t('annualRoundingLimit'))}`;}
function exerciseTwo(){return `<div class="grid"><div class="card blue"><h3>${t('entry')}</h3>${p(t('entryStory'))}</div><div class="card teal"><h3>${t('baseline')}</h3>${p(t('baselineStory'))}</div><div class="card orange"><h3>${t('top')}</h3>${p(t('topStory'))}</div></div><div class="controls">${selection('days',t('monthDays'),[[30,'30'],[60,'60']],state.days)}</div>${state.revealed?`<div class="grid two">${card(t('volume'),n(L.seasonal({annualMm3:100,share:.2,days:state.days}).volumeMm3),'Mm³')}${card(t('mean'),n(L.seasonal({annualMm3:100,share:.2,days:state.days}).meanM3s),'m³/s')}</div>${methodLab()}${details(t('recordStory').split(':')[0],p(t('recordStory'))+`<table><thead><tr><th>${t('rank')}</th><th>${t('factor')}</th><th>${t('probability')}</th></tr></thead><tbody>${[49,50,74,75,94,95].map(i=>`<tr><td>${i+1}</td><td>${n(base.reference.annualFactors[i],6)}</td><td>${n((i+1)/101*100,2)}%</td></tr>`).join('')}</tbody></table>`+savedAnnualArithmetic())}${details(t('timing'),timingFigure())}${details(t('top'),habitatFigure())}`:''}`;}
function allocationFigure(r){let s=txt(70,64,'3 m³/s')+line(60,145,265,145,'#24769a',18);s+='<circle cx="290" cy="145" r="20" fill="#d9e8df" stroke="#157466"/>';s+=line(310,138,675,70,'#b45d28',10)+line(310,148,675,160,'#24769a',14)+line(300,163,675,260,'#638b57',8);s+=txt(500,47,t('irrigation'))+txt(710,77,n(state.irrigation)+' m³/s')+txt(500,135,t('downstream'))+txt(710,168,state.revealed?n(r.downstream)+' m³/s':'?')+txt(500,245,t('wetland'))+txt(710,267,'0.5 m³/s')+txt(55,187,t('available'));return svg(t('calculator'),s,'',315);}
function exerciseThree(){const r=L.allocation({inflow:3,irrigation:state.irrigation,wetland:.5});return `<div class="controls">${selection('irrigation',t('irrigation'),[[1,'1 m³/s'],[.5,'0.5 m³/s']],state.irrigation)}</div>${allocationFigure(r)}${state.revealed?`<div class="grid">${card(t('downstream'),n(r.downstream),'m³/s','blue')}${card(t('dischargeDeficit'),n(r.riverDeficit),'m³/s','teal')}${card(t('unmet'),n(r.irrigationDeficit),'m³/s','orange')}</div><p class="note">Δ = ${n(r.diversionDifferenceM3Day)} m³/${esc(t('day'))}; Σ = 3 m³/s</p>`:''}`;}
function nativeScenario(){const data=state.scenario==='normal-managed'?base:sharing,id=state.scenario;return {data,id,s:data?.scenarios?.[id],valid:compare().valid&&G.validateReplay(data,id).valid};}
function nativeControls(){return `<div class="controls"><label>${t('date')}<input id="date" type="date" min="2025-01-01" max="2025-12-31" value="${base?.dates?.[state.day]||'2025-07-01'}"></label><button id="summer">${t('summer')}</button>${selection('scenario',t('evidence'),[['dry-managed-sharing',t('sharing')],['normal-managed',t('managed')+' · 100%']],state.scenario)}</div><p class="note">R2b · ${esc(base?.dates?.[state.day])} · ${esc(t('delivered'))}</p>`;}
function exerciseFour(){const {s,valid}=nativeScenario();if(!valid)return `<div class="pending">${t('pending')}</div>`;const pri=base.scenarios['dry-managed'],sh=sharing.scenarios['dry-managed-sharing'],nat=base.scenarios['dry-natural'];return nativeControls()+`<h3>${t('fixedDryComparison')}</h3>`+chart([{values:pri.criteria.ecologicalM3s,label:t('need'),color:'#157466'},{values:nat.series.R2bM3s,label:t('natural'),color:'#90a5a5',dash:true},{values:pri.series.R2bM3s,label:t('priority'),color:'#24769a'},{values:sh.series.R2bM3s,label:t('sharing'),color:'#b45d28'}],lesson().title,[pri.criteria.ecologicalM3s,sh.series.R2bM3s])+p(t('gapNote'))+(state.revealed?`<div class="grid two">${card(t('priority'),n(pri.findings.ecological.shortfallVolumeM3/1e6,6),'Mm³ · 365 '+t('day'),'blue')}${card(t('sharing'),n(sh.findings.ecological.shortfallVolumeM3/1e6,6),'Mm³ · 365 '+t('day'),'orange')}</div><h3>${t('selectedLedger')}</h3><p class="note">${t(state.scenario==='normal-managed'?'managed':'sharing')} · ${esc(base.dates[state.day])} · ${esc(state.scenario)}</p><div class="table-wrap"><table><thead><tr><th>${t('component')}</th><th>${esc(base.dates[state.day])}</th><th>365 ${t('day')}</th></tr></thead><tbody>${[['request','requestM3s'],['irrigation','C1M3s'],['unmet','unmetRequestM3s'],['consumed','consumptionM3s'],['returnFlow','D1M3s'],['release','releaseM3s'],['spill','spillM3s'],['outlet','R2bM3s']].map(([label,key])=>{const a=s.series[key];return `<tr><td>${t(label)}</td><td>${a?n(a[state.day])+' m³/s':t('notApplicable')}</td><td>${a?n(a.reduce((x,y)=>x+y,0)*86400/1e6,6)+' Mm³':t('notApplicable')}</td></tr>`;}).join('')}<tr><td>${t('storage')}</td><td>${n(s.series.storageM3[state.day])} m³</td><td>${t('notApplicable')}</td></tr></tbody></table></div>${details(t('natural'),p(t('nativeTransform'))+counterpartFigure())}<p class="evidence-id">${esc(s.provenance.datasetId)} / ${esc(s.id)} / ${esc(s.criteria.ecologicalVersion||s.criteria.policyVersion)} / ${esc(s.criteria.issuedVersion||s.criteria.policyVersion)}</p>`:'');}
function counterpartFigure(){let s=txt(40,35,t('natural'))+txt(480,35,t('managed'));s+=line(45,90,160,90)+line(185,90,300,90)+line(325,90,405,90)+line(490,90,595,90)+line(620,90,725,90)+line(750,90,855,90);s+=txt(40,70,'R1')+txt(145,70,'−5%')+txt(290,70,'S1*')+txt(385,70,'R2b')+txt(480,70,'R1')+txt(570,70,'−5%')+txt(710,70,'S1')+txt(835,70,'R2b');s+='<rect x="705" y="77" width="38" height="28" rx="5" fill="#a4d0d8"/><path d="M620 90 L660 180 L790 180 L820 95" fill="none" stroke="#b45d28" stroke-width="4" marker-end="url(#arrow)"/>';s+=txt(642,215,'C1 → 50% ET → D1','small')+txt(40,150,t('naturalOrigin'),'small')+txt(40,175,'S1* · '+t('storage')+' = 0','small');return svg(t('nativeTransform'),s,'',250);}
function mixFigure(r){let s=line(90,72,330,165,'#24769a',14)+line(90,250,330,165,'#b45d28',9)+line(355,165,675,165,'#795bb0',20);s+=txt(45,37,t('upstream'))+txt(45,62,'2 m³/s · 100 mg/L')+txt(45,286,t('drain'))+txt(45,309,'0.5 m³/s · '+n(800*state.factor)+' mg/L')+txt(610,120,'2.5 m³/s')+txt(620,210,state.revealed?n(r.concentrationMgL)+' mg/L':'? mg/L');s+=`<rect x="355" y="235" width="${r.loadGps/600*380}" height="22" rx="4" fill="#795bb0"/>`+txt(355,283,t('salt')+' · '+(state.revealed?n(r.loadGps):'?'));return svg(t('concentration'),s,'',335);}
function exerciseFive(){const r=L.mix({riverQ:2,riverC:100,drainQ:.5,drainC:800*state.factor});return `<div class="controls">${range('factor',t('sourceFactor'),state.factor,0,1,.1)}</div>${mixFigure(r)}${state.revealed?`<div class="grid">${card(t('flow'),n(r.flowM3s),'m³/s','blue')}${card(t('salt'),n(r.loadGps),'g/s','orange')}${card(t('concentration'),n(r.concentrationMgL),'mg/L','teal')}</div>`:''}`;}
function gapFigure(){return svg(lesson().title,`<rect x="65" y="50" width="730" height="55" fill="#e4ebe0"/><rect x="65" y="50" width="365" height="55" fill="#24769a"/><rect x="430" y="50" width="146" height="55" fill="#b45d28"/><rect x="576" y="50" width="219" height="55" fill="#a7b7ae"/>${txt(245,83,'5','','middle')}${txt(500,83,'2','','middle')}${txt(690,83,'3','','middle')}${txt(65,145,t('delivered'),'small')}${txt(430,170,t('shortfall'),'small')}${txt(600,145,t('naturalShortage'),'small')}${txt(65,220,t('need')+' 10 = 5 + 2 + 3')}${txt(65,252,t('issued')+' 7 = 5 + 2')}`,'',285);}
function uncertaintyFigure(){
 const left=state.value-state.halfWidth,right=state.value+state.halfWidth;
 const x=v=>85+(Math.max(5,Math.min(9,v))-5)*180;
 let out=`<line x1="85" y1="135" x2="805" y2="135" stroke="#536a70" stroke-width="2"/>`;
 for(let v=5;v<=9;v+=1)out+=`<line x1="${x(v)}" y1="130" x2="${x(v)}" y2="145" stroke="#536a70"/>`+txt(x(v),164,n(v),'small','middle');
 out+=`<line x1="${x(7)}" y1="45" x2="${x(7)}" y2="145" stroke="#157466" stroke-width="3" stroke-dasharray="6 4"/>`+txt(x(7),27,t('issued')+' = 7','small','middle');
 if(!state.missing){
  out+=`<rect x="${x(left)}" y="72" width="${Math.max(0,x(right)-x(left))}" height="38" rx="6" fill="#c3d9eb" stroke="#24769a"/>`;
  if(left<5)out+='<path d="M98 80 L85 91 L98 102" fill="none" stroke="#24769a" stroke-width="3"/>';
  if(right>9)out+='<path d="M792 80 L805 91 L792 102" fill="none" stroke="#24769a" stroke-width="3"/>';
 }
 out+=`<circle cx="${x(state.value)}" cy="91" r="7" fill="#24769a" stroke="#fff" stroke-width="2"/>`;
 out+=txt(85,202,t('measurement')+': '+n(state.value),'small');
 out+=txt(805,202,state.missing?t('not_assessed'):'['+n(left)+'; '+n(right)+'] m³/s','small','end');
 return svg(t('uncertainty'),out,state.missing?t('missingUncertainty'):t('uncertainty')+': ± '+n(state.halfWidth),225);
}
function floorLocationsFigure(){
 let out='<rect x="35" y="40" width="340" height="145" rx="12" fill="#edf4ef" stroke="#bed2c5"/><rect x="500" y="40" width="365" height="145" rx="12" fill="#fff5e9" stroke="#dec7ac"/>';
 out+=txt(55,70,t('upstream'),'small')+txt(55,102,t('issued')+' 7 / 7','small')+txt(55,146,t('met'),'small');
 out+=line(390,110,485,110,'#795bb0',2,'7 5');
 out+=txt(520,70,t('downstream'),'small')+txt(520,102,t('floorThreshold')+' = min(2, 3) = 2','small')+txt(520,134,t('siteActual')+' = 1.5','small')+txt(520,166,t(state.attribute?'attributed_shortfall':'unresolved'),'small');
 return svg(t('floorThreshold'),out,t('calculator'),210);
}
function exerciseSix(){const outcome=L.interval({value:state.value,halfWidth:state.missing?null:state.halfWidth,criterion:7}),floor=L.floorCheck({floor:2,butFor:3,actual:1.5,attributed:state.attribute,evidence:state.attribute});return gapFigure()+`<div class="controls">${range('value',t('measurement'),state.value,5,9,.5)}${range('halfWidth',t('uncertainty'),state.halfWidth,0,1,.25)}${check('missing',t('missingUncertainty'),state.missing)}</div>${uncertaintyFigure()}${state.revealed?`<div class="grid two">${card(t('status'),t(outcome))}${card(t('issued'),'7','m³/s')}</div>${details(t('threeDays'),p(t('threeNote')))}${details(t('detail'),p(t('floorStory'))+floorLocationsFigure()+`<div class="controls">${check('attribute',t('attribute'),state.attribute)}</div>`+card(t('status'),t(floor.verdict)))}${planningFigure()}`:''}`;}
function planningFigure(){return svg(t('adopt'),line(110,100,315,100)+line(340,100,560,100)+line(590,100,805,100)+txt(65,65,t('candidate'),'small')+txt(275,145,t('adopt'),'small')+txt(535,65,t('operate'),'small')+txt(660,145,t('monitor'),'small')+'<path d="M805 175 Q430 280 100 175" fill="none" stroke="#795bb0" stroke-width="3" stroke-dasharray="7 5" marker-end="url(#arrow)"/>'+txt(450,240,t('trigger'),'small','middle'),'',275);}
function wrapped(x,y,value,width){const words=value.split(' '),lines=[];let line='';for(const word of words){if((line+' '+word).length>Math.floor(width/5.6)&&line){lines.push(line);line=word;}else line+=(line?' ':'')+word;}if(line)lines.push(line);return lines.map((v,i)=>txt(x,y+i*12,v,'small')).join('');}
function modelRoles(){const box=(x,y,w,h,name,desc)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="12" fill="#fff" stroke="#b5c9bf"/>${txt(x+15,y+29,name)}${wrapped(x+15,y+53,desc,w-30)}`;let s=line(250,110,330,110)+line(615,140,740,227,'#795bb0',2,'7 5')+line(435,245,435,155)+line(470,155,470,245)+line(440,65,735,65,'#795bb0',2,'7 5')+line(790,102,790,227,'#795bb0',2,'7 5')+line(770,303,460,357,'#795bb0',2,'7 5')+'<path d="M290 392 L265 392 L265 33" fill="none" stroke="#795bb0" stroke-width="2" stroke-dasharray="7 5" marker-end="url(#arrow)"/>';s+=box(20,75,230,82,'SWAT+',t('swatRole'))+box(330,75,285,82,'Taqsim',t('taqRole'))+box(330,245,285,82,'MODFLOW 6',t('mfRole'))+box(685,227,195,82,'Fishy',t('fishRole'))+box(265,0,350,64,t('fieldEvidence'),'')+box(290,357,360,72,t('monitor'),'');return svg(t('modelRoles'),s,t('modelRoles'),445)+`<div class="legend"><span class="key" style="--key:#437f82">${t('flowArrow')}</span><span class="key" style="--key:#795bb0">⋯ ${t('evidenceArrow')}</span></div>`;}
function renderExtensions(){const e=C.catalogs[state.lang].extensionItems;$('extensions').innerHTML=`<p class="eyebrow">${t('extensions')}</p><h2>${t('modelRoles')}</h2>${modelRoles()}${p(t('extensionIntro'))}<div class="extension-grid">${e.map((item,i)=>`<details${i===4?' class="wide"':''}><summary>${esc(item.title)}</summary><div>${p(item.body)}</div></details>`).join('')}</div><div class="exercise-links">${link('guided.html','guided')}${link('assessment.html','assessment')}${link('playground.html','laboratory')}${link('index.html','large')}</div>`;}
function renderSources(){const c=C.catalogs[state.lang];$('sources').innerHTML=`<p class="eyebrow">${t('sources')}</p><h2>${t('sources')}</h2>${p(t('sourcesNote'))}${details(t('detail'),`<div class="exercise-links"><a href="https://lex.uz/uz/docs/-7655343" target="_blank" rel="noopener">Uzbek Water Code · Art. 4, 122 ↗</a><a href="https://www.fedlex.admin.ch/eli/cc/1992/1860_1860_1860/en" target="_blank" rel="noopener">GSchG · Art. 31–33 ↗</a><a href="coverage-matrix.json">${t('capabilities')} ↗</a><a href="controlled-terms.json">${t('termRegistry')} ↗</a><a href="data/guided.json">guided-six-unit-synthetic-v1 · JSON</a><a href="data/guided-sharing.json">guided-sharing-synthetic-v1 · JSON</a></div>${p(t('capabilityNote'))}<p class="evidence-id">Appendix A: steps 1–12 · Appendix B: B.0–B.9 · Part IV: quality coupling · ${esc(C.terminologyVersion)}</p>`)}${p(t('termsNote'))}<dl>${c.glossary.map(g=>`<dt>${esc(g.term)}</dt><dd>${esc(g.meaning)}</dd>`).join('')}</dl>`;}
function render(){const l=lesson();document.documentElement.lang=state.lang;document.title=t('title')+' · E-FLOW LAB';$('language').value=state.lang;$('language').setAttribute('aria-label',t('language'));$('chapters').setAttribute('aria-label',t('journey'));for(const [id,key]of Object.entries({'skip':'skip','header-note':'kicker','language-label':'language','journey-label':'journey','orientation':'orientation','extension-link':'extensions','source-link':'sources','hero-kicker':'kicker','hero-title':'title','hero-intro':'intro','scope':'scope','footer':'footer'}))$(id).textContent=t(key);$('chapters').innerHTML=C.catalogs[state.lang].lessons.map((l,i)=>`<button data-exercise="${i+1}" ${state.exercise===i+1?'class="active" aria-current="step"':''}><span class="num">${i+1}</span><span>${esc(l.title)}</span></button>`).join('');const exercise=[exerciseOne,exerciseTwo,exerciseThree,exerciseFour,exerciseFive,exerciseSix][state.exercise-1]();$('lesson').innerHTML=`<div class="lesson-head"><span class="big-num">0${state.exercise}</span><div><p class="eyebrow">${t(state.exercise===4?(nativeScenario().valid?'native':'pending'):'calculator')}</p><h2>${esc(l.title)}</h2></div></div><p class="intro">${esc(l.intro)}</p>${exercise}<section class="question"><form id="prediction"><fieldset><legend>${esc(l.question)}</legend><div class="choices">${l.options.map((o,i)=>`<label class="choice"><input type="radio" name="prediction" value="${i}"${state.answer===i?' checked':''} required><span>${esc(o)}</span></label>`).join('')}</div></fieldset><div class="actions"><button class="primary" type="submit">${t('check')}</button><button type="button" id="retry">${t('retry')}</button><button type="button" id="reset">${t('reset')}</button></div></form><div aria-live="polite">${state.revealed?`<div class="feedback ${state.answer===l.answer?'':'review'}"><strong>${t(state.answer===l.answer?'right':'reconsider')}</strong>${p(l.feedback)}</div>`:''}</div></section>${state.revealed?`<section class="result"><h3>${t('result')}</h3>${details(t('detail'),p(l.detail),true)}${details(t('real'),p(l.real),true)}<div class="actions"><button id="export-json">${t('download')}</button><button id="export-card">${t('readable')}</button></div></section>`:''}<div class="next-row"><button data-exercise="${Math.max(1,state.exercise-1)}"${state.exercise===1?' disabled':''}>${t('previous')}</button><button data-exercise="${Math.min(6,state.exercise+1)}"${state.exercise===6?' disabled':''}>${t('next')}</button></div>`;renderExtensions();renderSources();persist();}
function currentResult(){switch(state.exercise){case 1:return {route:G.classify({origin:state.origin,designation:state.designation,designationValidity:state.designation==='designated'?'valid':null}),classificationChangesPhysics:false};case 2:{const run=P.runExperiment({pattern:state.pattern,meanFlow:5,supplyFactor:state.supply,designClass:50,riskFloor:state.risk==='missing'?null:state.risk==='cross'?50:.8,habitatTarget:.7});return {practice:L.seasonal({annualMm3:100,share:.2,days:state.days}),methods:run.methods.map(m=>({id:m.id,annualVolumeMm3:m.annualVolumeMm3,requirement:m.requirement})),notNative:true};}case 3:return L.allocation({inflow:3,irrigation:state.irrigation,wetland:.5});case 4:{const {s,valid}=nativeScenario();return valid?{admitted:true,daily:Object.fromEntries(Object.entries(s.series).map(([key,a])=>[key,a[state.day]])),ecologicalCriterion:s.criteria.ecologicalM3s[state.day],issuedCriterion:s.criteria.issuedM3s[state.day],ecologicalFinding:s.findings.ecological.daily[state.day],issuedFinding:s.findings.issued.daily[state.day],annualEcologicalShortfallM3:s.findings.ecological.shortfallVolumeM3,comparison:sharing.comparison}: {admitted:false};}case 5:return L.mix({riverQ:2,riverC:100,drainQ:.5,drainC:800*state.factor});case 6:return {ecologicalGap:5,naturalGap:3,instructionShortfall:2,interval:L.interval({value:state.value,halfWidth:state.missing?null:state.halfWidth,criterion:7}),floor:L.floorCheck({floor:2,butFor:3,actual:1.5,attributed:state.attribute,evidence:state.attribute}),ecologicalStatus:null,legalFault:null};}}
function record(){const native=state.exercise===4;return {schemaVersion:'eflow-learning/1',locale:state.lang,terminologyVersion:C.terminologyVersion,exercise:state.exercise,inputs:{...state,answer:state.answer,revealed:true},result:currentResult(),caseId:native?'guided-native-comparison-v1':'learning-exercise-'+state.exercise+'-v1',datasetId:native?nativeScenario().data?.datasetId:null,scenarioId:native?state.scenario:null,referenceId:native?base.reference.version:null,selectedDate:native?base.dates[state.day]:null,checkpoint:native?'R2b':null,decisionStatus:'teaching_candidate_not_adopted',reviewTrigger:t('reviewTriggerText'),reviewDate:null,reviewDateReason:t('datePending'),evidenceToObtain:lesson().real,actionOwnerRole:t('nextRole'),planUnitStatus:state.plan?'fictional_PU-demo':'unassigned',ecologicalStatus:null,legalFault:null,readable:{title:lesson().title,question:lesson().question,prediction:lesson().options[state.answer],explanation:lesson().feedback,limits:lesson().detail,nextAction:lesson().real},returnUrl:url()};}
function resultRows(){const r=currentResult();switch(state.exercise){case 1:return [[t('body'),state.body],[t('origin'),t(state.origin==='natural'?'naturalOrigin':'artificial')],[t('status'),t(r.route==='potential'?'potentialRoute':r.route==='natural/status'?'statusRoute':'undetermined')]];case 2:return [[t('annual'),'100 Mm³'],[t('share'),'20%'],[t('monthDays'),n(state.days)],[t('volume'),n(r.practice.volumeMm3)+' Mm³'],[t('mean'),n(r.practice.meanM3s)+' m³/s'],...r.methods.map((m,i)=>[t(['entry','baseline','top'][i]),m.requirement?n(m.annualVolumeMm3)+' Mm³':t('unavailable')])];case 3:return [[t('available'),'3 m³/s'],[t('wetland'),'0.5 m³/s'],[t('irrigation'),n(state.irrigation)+' m³/s'],[t('downstream'),n(r.downstream)+' m³/s'],[t('dischargeDeficit'),n(r.riverDeficit)+' m³/s'],[t('unmet'),n(r.irrigationDeficit)+' m³/s']];case 4:return r.admitted?[[t('delivered'),n(r.daily.R2bM3s)+' m³/s'],[t('need'),n(r.ecologicalCriterion)+' m³/s'],[t('issued'),n(r.issuedCriterion)+' m³/s'],[t('deficit'),n(r.annualEcologicalShortfallM3/1e6,6)+' Mm³'],[t('status'),t(r.ecologicalFinding)]]:[[t('status'),t('pending')]];case 5:return [[t('sourceFactor'),n(state.factor)],[t('flow'),n(r.flowM3s)+' m³/s'],[t('salt'),n(r.loadGps)+' g/s'],[t('concentration'),n(r.concentrationMgL)+' mg/L']];case 6:return [[t('need'),'10 m³/s'],[t('issued'),'7 m³/s'],[t('delivered'),'5 m³/s'],[t('measurement'),n(state.value)+' m³/s'],[t('uncertainty'),state.missing?t('unknown'):n(state.halfWidth)+' m³/s'],[t('status'),t(r.interval)],[t('detail'),t(r.floor.verdict)]];}}
function save(kind){if(!state.revealed)return;const r=record();const text=kind==='json'?JSON.stringify(r,null,2):[r.readable.title,r.readable.question,r.readable.prediction,'',t('result'),r.readable.explanation,'',...resultRows().map(([k,v])=>k+': '+v),'',t('detail'),r.readable.limits,'',t('real'),r.evidenceToObtain,'',t('status')+': '+t('candidate'),t('owner')+': '+r.actionOwnerRole,t('trigger')+': '+r.reviewTrigger,t('reviewDate')+': '+r.reviewDateReason,t('body')+': '+state.body,t('checkpoint')+': '+(r.checkpoint||t('notApplicable')),t('date')+': '+(r.selectedDate||t('notApplicable')),t('evidence')+': '+r.caseId+(r.datasetId?' / '+r.datasetId+' / '+r.scenarioId:''),'',t('footer')].join('\n');const blob=new Blob([text],{type:kind==='json'?'application/json':'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`eflow-learning-${state.exercise}-${state.lang}.${kind==='json'?'json':'txt'}`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function reset(fresh){state.answer=null;state.revealed=false;state.variant=fresh?state.variant+1:0;if(fresh){if(state.exercise===1){state.mode=state.mode==='network'?'landscape':'network';state.designation=state.designation==='none'?'not_searched':'none';}if(state.exercise===2){state.days=state.days===30?60:30;state.pattern=state.pattern==='snowmelt'?'rainfall':'snowmelt';}if(state.exercise===3)state.irrigation=state.irrigation===1?.5:1;if(state.exercise===4)state.day=(state.day+60)%365;if(state.exercise===5)state.factor=state.factor===1?.5:1;if(state.exercise===6){state.value=state.value===7?6:7;state.missing=false;}}else{state.irrigation=1;state.days=30;state.factor=1;state.day=181;state.value=7;state.halfWidth=.5;state.missing=false;state.attribute=false;state.designation='not_searched';}render();}
document.addEventListener('submit',event=>{if(event.target.id!=='prediction')return;event.preventDefault();const selected=new FormData(event.target).get('prediction');if(selected===null)return;state.answer=Number(selected);state.revealed=true;render();});
document.addEventListener('change',event=>{const el=event.target,id=el.id;if(id==='language'){state.lang=el.value;try{localStorage.setItem('eflow-language',state.lang);}catch(_error){}render();return;}if(el.name==='prediction'){state.answer=Number(el.value);return;}if(id==='date'){const day=base.dates.indexOf(el.value);if(day>=0)state.day=day;}else if(id==='body'){state.body=el.value;state.origin=['C1','D1','S1'].includes(state.body)?'artificial':'natural';state.designation='not_searched';}else if(Object.hasOwn(state,id)){state[id]=el.type==='checkbox'?el.checked:['day','days','irrigation','factor','supply','value','halfWidth'].includes(id)?Number(el.value):el.value;}else return;render();});
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.dataset.exercise){state.exercise=Number(b.dataset.exercise);state.variant=0;state.revealed=false;state.answer=null;render();$('lesson').focus();}else if(b.id==='summer'){state.day=181;render();}else if(b.id==='retry')reset(true);else if(b.id==='reset')reset(false);else if(b.id==='export-json')save('json');else if(b.id==='export-card')save('card');});
render();
})();
