/* Display-only localization. Frozen inputs, results, identifiers and criterion arrays are never translated in place. */
(function(root){
'use strict';
const locales=['en','ru','uz-Latn'],numberLocales={en:'en-GB',ru:'ru-RU','uz-Latn':'uz-Latn-UZ'};
const params=new URLSearchParams(location.search);let preference='en';try{preference=localStorage.getItem('eflow-locale')||'en';}catch{}
let language=locales.includes(params.get('lang'))?params.get('lang'):locales.includes(preference)?preference:'en';
const sourceTitle=document.title;
const messages=new Map(),templates=[],missing=new Set(),originals=new WeakMap(),attributeSources=new WeakMap();
const normal=s=>s.replace(/\s+/g,' ').trim();
const escape=s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
for(const catalog of root.EflowLegacyCatalogs||[])for(const row of catalog.messages){const [source,ru,uz]=row;messages.set(normal(source),{en:source,ru,'uz-Latn':uz});if(source.includes('{')){const keys=[];let pattern='',last=0;for(const match of source.matchAll(/\{(\w+)\}/g)){pattern+=escape(normal(source.slice(last,match.index))).replace(/^ | $/g,'');if(last&&source[last]===' ')pattern=''+pattern;keys.push(match[1]);last=match.index+match[0].length;}const parts=normal(source).split(/\{\w+\}/);templates.push({specificity:parts.join('').length,regex:new RegExp('^'+parts.map(escape).join('(.+?)')+'$'),keys,values:{ru,'uz-Latn':uz}});}}
templates.sort((a,b)=>b.specificity-a.specificity);
for(const t of templates)if(t.specificity>50&&/[.!?]\$$/.test(t.regex.source))t.prefixRegex=new RegExp(t.regex.source.slice(0,-1)+'(?= |$)');
const phraseSources=[...messages.keys()].filter(k=>k.length>5&&!k.includes('{')&&/[.!?:]$/.test(k)).sort((a,b)=>b.length-a.length);
function translateCore(source,depth=0){if(typeof source!=='string'||language==='en')return source;const key=normal(source);if(!key)return source;const exact=messages.get(key)?.[language];if(exact)return exact;if(depth<10){if(/^[.;]\s/.test(key)){const rest=translate(key.slice(2),depth+1);if(rest!==key.slice(2))return key.slice(0,2)+rest;}for(const prefix of phraseSources){if(key.startsWith(prefix+' ')){const rest=key.slice(prefix.length+1);return messages.get(prefix)[language]+' '+translate(rest,depth+1);}}for(const t of templates){if(t.prefixRegex){const lead=key.match(t.prefixRegex);if(lead&&lead[0].length<key.length){let target=t.values[language];t.keys.forEach((k,i)=>target=target.replaceAll('{'+k+'}',translate(lead[i+1],depth+1)));return target+' '+translate(key.slice(lead[0].length).trim(),depth+1);}}const match=key.match(t.regex);if(match){let target=t.values[language];t.keys.forEach((k,i)=>target=target.replaceAll('{'+k+'}',translate(match[i+1],depth+1)));return target;}}const sentences=key.split(/(?<=[.!?])\s+(?=[A-Z])/);if(sentences.length>1){const converted=sentences.map(s=>translate(s,depth+1));if(converted.every((s,i)=>s!==sentences[i]||!/[A-Za-z]{3}/.test(s)))return converted.join(' ');}for(const separator of ['; ', ', ', ' / ']){const parts=key.split(separator);if(parts.length>1){const translated=parts.map(p=>translate(p,depth+1));if(translated.every((p,i)=>p!==parts[i]||!/[A-Za-z]{3}/.test(p)))return translated.join(separator);}}}
if(/[A-Za-z]{3}/.test(key)&&!/^([\w.-]+:)?[\w.-]+-(?:v\d|20\d\d)|^[a-f0-9]{64}$/.test(key))missing.add(key);return source;}
function translate(source,depth=0){const out=translateCore(source,depth);if(typeof source!=='string'||out===source)return out;return (source.match(/^\s*/)?.[0]||'')+out+(source.match(/\s*$/)?.[0]||'');}
function validReturn(value){if(!value)return null;try{const u=new URL(value,location.href);if(u.origin!==location.origin||!u.pathname.endsWith('/learn.html')||value.startsWith('//')||/^[a-z]+:/i.test(value))return null;u.searchParams.set('lang',language);return 'learn.html'+u.search+u.hash;}catch{return null;}}
const returnTo=validReturn(params.get('returnTo'));
function keepQuery(query){query.set('lang',language);if(returnTo)query.set('returnTo',validReturn(returnTo));return query;}
function decorateLinks(){for(const a of document.querySelectorAll('a[href]')){const href=a.getAttribute('href');if(!/^(guided|assessment|playground|index|learn)\.html(?:[?#]|$)/.test(href||''))continue;const u=new URL(href,location.href);u.searchParams.set('lang',language);if(returnTo&&!u.pathname.endsWith('/learn.html'))u.searchParams.set('returnTo',validReturn(returnTo));const target=u.pathname.split('/').at(-1)+u.search+u.hash;if(href!==target)a.setAttribute('href',target);}}
function apply(){observer?.disconnect();const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let node;while((node=walker.nextNode())){if(node.parentElement?.closest('script,style,pre,code,[data-i18n-ignore]'))continue;const previous=originals.get(node),source=previous&&node.nodeValue===previous.translated?previous.source:node.nodeValue;const translated=translate(source);originals.set(node,{source,translated});if(node.nodeValue!==translated)node.nodeValue=translated;}for(const el of document.querySelectorAll('[aria-label],[title],[placeholder],[label]' ))for(const attr of ['aria-label','title','placeholder','label'])if(el.hasAttribute(attr)){const cache=attributeSources.get(el)||{},previous=cache[attr],current=el.getAttribute(attr),source=previous&&current===previous.translated?previous.source:current,value=translate(source);cache[attr]={source,translated:value};attributeSources.set(el,cache);if(current!==value)el.setAttribute(attr,value);}decorateLinks();observer?.observe(document.body,{childList:true,subtree:true,characterData:true,attributes:true,attributeFilter:['aria-label','title','placeholder','label']});}
let observer=null;
function start(){document.documentElement.lang=language;document.title=translate(document.title);const bar=document.createElement('div');bar.className='locale-bar';bar.innerHTML='<a id="learning-return"></a><label for="legacy-language">'+'Language'+'</label><select id="legacy-language"><option value="en">English</option><option value="ru">Русский</option><option value="uz-Latn">Oʻzbekcha (lotin)</option></select><span>'+'Technical identifiers stay unchanged. Translations are provisional, not official terminology approval.'+'</span><a href="controlled-terms.json">'+'Terminology sources and review status'+'</a>';document.body.prepend(bar);const back=bar.querySelector('a');back.href=returnTo||'learn.html?lang='+language;back.textContent=returnTo?'Return to your learning exercise':'Open the learning journey';bar.querySelector('select').value=language;bar.querySelector('select').onchange=e=>{const lang=e.target.value;try{localStorage.setItem('eflow-locale',lang);}catch{}const q=new URLSearchParams(location.search);q.set('lang',lang);language=lang;document.documentElement.lang=lang;document.title=translate(sourceTitle);history.replaceState(null,'','?'+keepQuery(q).toString());back.href=validReturn(returnTo)||'learn.html?lang='+lang;if(typeof root.render==='function'){if(location.pathname.endsWith('/assessment.html')){const body=document.getElementById('case-select').value,variant=document.getElementById('variant-select').value;if(body&&variant)root.render(body,variant);}else root.render();}apply();};for(const pre of document.querySelectorAll('pre')){const p=document.createElement('p');p.className='small technical-note';p.textContent='Technical source record: stable keys, IDs and original provenance remain unchanged. Use the translated summary for interpretation.';pre.before(p);}observer=new MutationObserver(apply);apply();}
function withLocale(record){const outputLabels={entry_floor_candidate:'Illustrative floor only',seasonal_quantity_candidate:'Seasonal quantity candidate',habitat_element_candidate:'Habitat element candidate',potential_pending:'Potential sizing pending',receptor_pending:'Receptor sizing pending',track_undetermined:'Track undetermined',calculation_pending:'Calculation pending',route_only_natural:'Natural route · calculation pending'};const summary={language,explanation:translate('Translated interpretation. Original technical fields, identifiers and numerical arrays remain unchanged.'),datasetId:record.datasetId||null,waterBodyId:record.waterBodyId||record.contextOnly?.waterBodyId||null,checkpoint:record.checkpoint||null,selectedDate:record.selectedDate||null,scenarioId:record.scenarioId||null,scenarioName:record.scenarioName?translate(record.scenarioName):null,assessmentRoute:record.track?translate(record.track):null,output:record.outputKind?translate(outputLabels[record.outputKind]||record.outputKind):null,ecologicalStatus:translate(record.ecologicalStatus||'Not established'),nextAction:record.nextAction?translate(record.nextAction):null,responsibleRole:record.responsibleRole?translate(record.responsibleRole):null,reviewTrigger:record.reviewTrigger?translate(record.reviewTrigger):null,routeReasons:(record.reasons||[]).map(v=>translate(v)),finalRequirementReason:record.finalRequirement?.reason?translate(record.finalRequirement.reason):null,timeSupport:typeof record.timeSupport==='string'?translate(record.timeSupport):record.timeSupport||null,flowCriterionBasis:record.flowCriterionBasis?translate(record.flowCriterionBasis):null,fieldLabels:{flowM3s:translate('Flow'),annualVolumeMm3:translate('Required · million m³'),saltMgL:translate('Salinity'),shortfallDays:translate('Shortfall days')},pendingReasons:record.pending?Object.fromEntries(Object.entries(record.pending).map(([key,v])=>[key,{reason:translate(v.reason),nextAction:translate(v.nextAction),responsibleRole:translate(v.responsibleRole),reviewTrigger:translate(v.reviewTrigger)}])):null,omittedLimbs:(record.omittedLimbs||[]).map(v=>translate(v)),assumptions:(record.assumptions||record.result?.assumptions||[]).map(v=>translate(v)),methods:(record.result?.methods||[]).map(m=>({methodId:m.id,name:translate(m.name),reason:translate(m.reason),annualVolumeMm3:m.annualVolumeMm3,shortfallVolumeMm3:m.shortfallVolumeMm3,shortfallDays:m.shortfallDays})),selectedDay:record.selectedDay||null,findings:record.findings?{explanation:translate('Quantity findings support a planning decision. They do not establish ecological status.'),flowShortfallDays:record.findings.shortfall_days,saltExceedanceDays:record.findings.salt_exceedance_days,dryDays:record.findings.dry_days}:null};return {...record,locale:language,terminologyVersion:'2026-10-04-provisional-1',localizedSummary:summary};}
root.EflowI18n={withLocale,locale:()=>language,t:translate,number:(v,d=2)=>Number.isFinite(v)?v.toLocaleString(numberLocales[language],{maximumFractionDigits:d}):translate('Pending'),dateLocale:()=>numberLocales[language],date:(date,options={})=>language==='uz-Latn'?date.toISOString().slice(0,10):date.toLocaleDateString(numberLocales[language],options),keepQuery,validReturn,decorateLinks,apply,coverage:()=>({locale:language,missing:[...missing].sort(),catalogMessages:messages.size,templates:templates.length}),readable:text=>text.split('\n').map(line=>translate(line)).join('\n')};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})(globalThis);
